# Numpy Arrays verbinden
Um aus zwei oder mehreren Arrays einen neuen gemeinsamen Array zu bilden, stehen uns mehrere Möglichkeiten zur Verfügung.



## Concatenate von ein- und mehrdimensionalen Arrays
Mit der Methode `concatenate` lassen sich ein- und mehrdimensionale Arrays zu einem Array verbinden. Wichtig zu verstehen ist hier der Achsenbegriff (axis). Axis 0 bezeichnet die Zeilen (rows), während Axis 1 die Spalten bezeichnet. 

**Generell kann man sagen: Der Shape des neuen Arrays verändert sich nur an der Achse, an dem die Arrays zusammengefügt werden**.

**Es können nur Arrays gleichen Shapes (gleicher Dimension) an der Nicht-Konkatenierungsachse konkateniert werden**


- axis=0 (Zeilenweise Konkatenation) → Spaltenzahl muss gleich sein.       
- axis=1 (Spaltenweise Konkatenation) → Zeilenzahl muss gleich sein. 

![title](numpy-arrays-have-axes.webp)

## Concatenate von zwei zweidimensionalen Arrays an Axis 0
Wenn wir concatenate auf Matrizen mit axis=0 durchführen, werden die Arrays "untereinandert" zusammengefügt. Das führt dazu, dass der Shape der Columns (Spalten) gleich bleibt, sich aber der Zeilenshape verändert. Die Arrays werden also vertikal "gestapelt". Dazu muss die Anzahl an Spalten in beiden Arrays übereinstimmen. Der Shape an Achse 0 hat sich verändert, der Spaltenshape blieb gleich.

![title](explanation_numpy-concatenate-axis-0.webp)

In [12]:
arr1 = np.array([[1, 1, 1], [1, 1, 1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9], [9, 9, 9]])


## Aber: 2 eindimensionale Arrays zu einem Array an der Achse 0 mit concatentate zusammenführen

Da eindimensionale Arrays nur eine Achse haben, führt hier das Verbinden an Achse 0 zu einem weiteren eindimensionalen Array. Der Shape an Stelle 0 hat sich verändert.

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])


## Aufgabe
Gegeben sind Vektor v mit 3 Elementen und eine 2 x 3 Matrix M.
Verbinde die beiden Objekte an der Achse 0 (Zeilen) zu einer neuen Matrix A.

Erinnerung: es können nur Arrays konkateniert werden, die den gleichen Shape an der NICHT-Konkatenierungsachse (hier Achse 1) haben. Forme v vor der Konkatenierung entsprechend um.

Das Ergebnis sollte so aussehen:

[[ 1  2  3]   
 [11 22 33]   
 [44 55 66]]    

In [14]:
# Happy Coding (5 Minuten)
v = np.array([1, 2, 3])
M = np.array([[11, 22, 33], [44, 55, 66]])


## Concatenate von zwei zweidimensionalen Arrays an Axis 1
Wenn wir concatenate mit axis=1 durchführen, werden die Arrays "nebeneinandert" zusammengefügt. Das führt dazu, dass der sich Shape der Columns (Spalten) verändert, der Zeilenshape aber gleich bleibt. 
![title](explanation_numpy-concatenate-axis-1.webp)

In [18]:
arr1 = np.array([[1, 1, 1], [1, 1, 1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])


## Vektor und Matrix via vstack zu einem mehrdimensionalen Array zusammenfügen
Um Arrays mit `concatenate` zu verbinden, müssen sie die gleichen Dimensionen haben. Somit lässt sich also kein ein- und mehrdimensionaler Array verbinden. Dazu gibt es die Methode `vstack`. vstack steht für vertikal Stapeln. 

Im Falle von vstack muss nur gegeben sein, dass beide Arrays die gleiche Anzahl an Spalten haben. Natürlich lassen sich auch zwei mehrdimensionale Arrays mit vstack verbinden.

In [19]:
arr1 = np.array([1, 1, 1])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])


## Zwei Matritzen via hstack zu einem mehrdimensionalen Array zusammenfügen
Um Arrays mit `concatenate` zu verbinden, müssen sie die gleichen Dimensionen haben. Somit lässt sich also kein ein- und mehrdimensionaler Array verbinden. Dazu gibt es die Methode `hstack`. hstack steht für horizontal Stapeln. 

Im Falle von vstack muss nur gegeben sein, dass beide Arrays die gleiche Anzahl an Zeilen haben. 

In [20]:
# zwei Arrays mit shape 2,1 und 2,3
arr1 = np.array([[1], [1]])
arr2 = np.array([[9, 9, 9], [9, 9, 9]])


## Aufgabe

In [16]:
import numpy as np

# 1D-Array mit den Beständen für 3 Standorte (6 Produkte pro Standort)
stock = np.array([100, 150, 80, 200, 50, 90,   # Zentrallager
                  60, 120, 70, 100, 30, 50,    # Filiale 1
                  40, 110, 60, 80, 20, 30])    # Filiale 2

# 1. Reshape auf 3 x 6 Matrix
stock_matrix = stock.reshape(3, 6)

# 2. Slice daraus eine Matrix über die ersten drei Spalten (Ergebnis wird nicht weiter benötigt)
selected_products = stock_matrix[:, :3]

# 3. Für zwei neue Filialen sollen die Produkte in die stock-Matrix via vstack eingefügt werden

new_delivery = np.array([[55, 130, 75, 95, 35, 60],  # Filiale 3
                         [45, 100, 65, 85, 25, 40]]) # Filiale 4


# 3. Simulierte Lieferung für zwei neue Filialen (2x6-Matrix)
final_stock_matrix = np.vstack((stock_matrix, new_delivery))
final_stock_matrix

array([[100, 150,  80, 200,  50,  90],
       [ 60, 120,  70, 100,  30,  50],
       [ 40, 110,  60,  80,  20,  30],
       [ 55, 130,  75,  95,  35,  60],
       [ 45, 100,  65,  85,  25,  40]])